### ISSUE TITLE
[BUG] : gif is too large for readme

### ISSUE THREAD

**Issue by PritamSarbajna** [Programing-School/Programing-School#5]
**Describe the bug**
I have attached below the screenshot that the gif is too large to fit inside readme. I saw that it's showing good in the website but if it's also inside the readme it'd be good

**Expected behavior**
The gif should be inside readme.

**Screenshots**

![Screenshot (191)](https://user-images.githubusercontent.com/90236635/184276917-0721272f-0afa-422b-b999-92d6576f8d4d.png)

**Comment by MOHAMED-EHAB-DEV** [comment]
You have a Problem 

![image](https://user-images.githubusercontent.com/96921717/199090206-8fffb6d8-2988-454a-aaa4-65aa9dbad128.png)
